config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :products
    resources :rewards
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/reward.rb
class Reward < ApplicationRecord

  #
  # constant
  #

  REWARDS = {
    coffee:     "Coffee",
    cash_back:  "5% Cash Back",
    movie:      "Free Movie Ticket",
    lounge:     "4x Airport Lounge Access",
    bounus:     "Quarterly Bonus"
  }
  
  #
  # association
  #

  belongs_to :user


  #
  # scope
  #

  default_scope { order(created_at: :desc) }
  scope :this_year, ->  { where(created_at: DateTime.current.all_year) }

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: %i[ show edit update destroy ]
  before_action :set_user

  # GET /rewards or /rewards.json
  def index
    @rewards = Reward.all
  end

  # GET /rewards/1 or /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards or /rewards.json
  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to reward_url(@reward), notice: "Congratulations! You got a Reward." }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1 or /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully updated." }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1 or /rewards/1.json
  def destroy
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url, notice: "Reward was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
        
    def set_user
      @user = User.find(params[:user_id])
    end
        
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reward_params
      params.require(:reward).permit(:name, :user_id)
    end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: [@user, @reward], class: "contents") do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-2">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="my-2">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn-primary" %>
  </div>
<% end %>

app/views/rewards/_reward.html.erb
<div id="<%= dom_id reward %>" class="w-full p-2 bg-gray-100 rounded hover:bg-gray-200">
  <p> <%= reward.name %> </p>
</div>

app/views/rewards/edit.html.erb
<h3>Editing reward</h3>

<%= render "form", reward: @reward %>

app/views/rewards/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h3>Rewards</h3>
    <%= link_to 'New reward', new_user_reward_path(@user), class: "btn-primary" %>
  </div>

  <div id="rewards" class="min-w-full">
    <%= render @rewards %>
  </div>
</div>

app/views/rewards/new.html.erb
<h3>New reward</h3>
<%= render "form", reward: @reward %>

app/views/rewards/show.html.erb
<div class="my-1">
  <%= link_to 'Back to rewards', user_rewards_path(@user), class: "btn-secondary" %>
</div>

<%= render @reward %>