config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :products
    resources :rewards
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord

  #
  # constant
  #

  TIER = {
    standard:   "Standard",
    gold:       "Gold",
    platinum:   "Platinum"
  }  


  after_save :post_save

  #
  # association
  #

  has_many :products
  has_many :rewards


  #
  # validation
  #

  validates :name, :dob, presence: true


  #
  # methods
  #

  def update_points(arg = nil)
    
    product = arg.nil? ? products : products.where(created_at: arg)

    amount_collection = product&.this_year&.collect {|e| e.country == "singapore" ? e.amount : 2*e.amount }
    # non_singapore_collection = product&.this_year&.collect {|e| 2*e.amount if e.country != "singapore" }

    total_amount = amount_collection&.compact&.inject(0) {|sum, number| sum + number} 
    # non_singapore_point = non_singapore_collection&.compact&.inject(0) {|sum, number| sum + number} 
    
    final_points = (((total_amount)/100).to_i)*10
          

    return points = 0 if final_points < 0
    
    return points = final_points + 100 if final_points >= 2000

    return points = final_points
  end


  private
      

  def post_save
    points = update_points(DateTime.current.all_month)
        
    # coffee reward
    if DateTime.current.month == dob.month
      Reward.create(name: Reward::REWARDS[:coffee], user_id: id) unless Reward.find_by(name: Reward::REWARDS[:coffee], user_id: id, created_at: DateTime.current.all_month)&.present?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_product
      @products = Product.all
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :dob, :points, :tier)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h3><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h3>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :tier, value: User::TIER[:standard] if user.points == 0 || user.points.nil? %>

  <div class="my-2">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="my-2">
    <%= form.label :dob, style: "display: block" %>
    <%= form.datetime_field :dob %>
  </div>

  <div>
    <%= form.submit class:"btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= link_to user do %>
  <div class="inline-grid w-full grid-cols-3 p-2 rounded <%= user.update_points >= 5000 ? 'border-2 border-cyan-300 bg-cyan-100' : (1000..4999).include?(user.update_points) ? 'border-2 border-amber-300 bg-amber-100' : 'border-2 border-stone-300 bg-stone-100' %> ">
    <p> <%= user.name %> </p>

    <p> <%= user.dob.strftime("%d %b %Y") %> </p>

    <p> <%= user.update_points %> </p>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Editing user</h3>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<div class="flex justify-between items-center">
  <h3>Users</h3>
  <%= link_to "New user", new_user_path, class:"btn-primary" %>
</div>

<div id="users">
  <div class="grid grid-cols-3 p-2 bg-gray-200 mb-2">
    <strong> Name </strong>
    <strong> DOB </strong>
    <strong> Points </strong>
  </div>

  <div class="grid gap-2">
    <%= render @users %>
  </div>

</div>
<br>

app/views/users/new.html.erb
<h3>New user</h3>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<div class="flex justify-between my-1">
  <%= link_to "< Back", users_path, class:"btn-secondary" %>
  <%= link_to "Edit this user", edit_user_path(@user), class:"btn-secondary" %>
</div>

<%#= render @user %>
<div class="grid grid-flow-col rounded p-2 <%= @user.update_points >= 5000 ? 'border-2 border-cyan-300 bg-cyan-100 ' : (1000..4999).include?(@user.update_points) ? 'border-2 border-amber-300 bg-amber-100 ' : 'border-2 border-stone-300 bg-stone-100' %> ">
  <div>
    <h3> <%= @user.name %> </h3>
    <p> <%= @user.dob.strftime("%d %b %Y") %> </p>
    <h3> <%= @user.update_points >= 5000 ? User::TIER[:platinum] : (1000..4999).include?(@user.update_points) ? User::TIER[:gold] : User::TIER[:standard] %> </h3>
  </div>
  <div class="md:flex justify-between lg:w-2/3">
    <div> <p> Points </p> <h4> <%= @user.update_points %> </h4>  </div>
    <div> <p> Transations </p> <h4> <%= @user.products.this_year.count %> </h4>  </div>
    <div> <p> Rewards </p> <h4> <%= @user.rewards.this_year.count %> </h4> </div>
  </div>
</div>


<br><br><br>
<hr>
<br>


<div class="grid lg:grid-cols-3 gap-8">
  <div class=" <%= @user.rewards.this_year.present? ? 'lg:col-span-2' : 'lg:col-span-3' %> ">
    <div class="flex justify-between items-center">
      <h3> Products </h3>
      <%= link_to "Add new product", new_user_product_path(@user), class:"btn-secondary" %>
    </div>


    <div class="grid gap-1">
      <div class="grid grid-cols-3 p-2 bg-gray-200 my-1">
        <strong> Name </strong>
        <strong> Amount Spend </strong>
        <strong> Country </strong>
      </div>
      <div class=" <%= @user.products.this_year.count > 7 ? 'lg:h-80 overflow-y-scroll' : '' %> ">
        <% @user.products.this_year.each do |product| %>
          <%= render 'products/product', product: product %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="lg:col-span-1">
    <% if @user.rewards.this_year.present? %>
      <h3> Rewards </h3>

      <div class="grid gap-1">
        <div class="p-2 bg-gray-200 my-1">
          <strong> Reward Name </strong>
        </div>
        <% @user.rewards.this_year.each do |reward| %>
          <%= render 'rewards/reward', reward: reward %>
        <% end  %>
      </div>
    <% end %>
  </div>
</div>