config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :products
    resources :rewards
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/product.rb
class Product < ApplicationRecord

  #
  # constant
  #

  COUNTRY = {
    singapore: "SINGAPORE",
    india:     "INDIA",
    other:     "OTHER"
  }

  #
  # callback
  #
  
  after_save :post_save


  #
  # scope
  #
  
  # default_scope { order(created_at: :desc) }
  scope :this_year, ->  { where(created_at: DateTime.current.all_year) }
  
  #
  # validation
  #

  validates :name, :amount, presence: true


  #
  # association
  #

  belongs_to :user


  private
      

  def post_save

    points = user.update_points(DateTime.current.all_month)
          
    # coffee reward
    if points >= 100 || DateTime.current.month == user.dob.month
      Reward.create(name: Reward::REWARDS[:coffee], user_id: user.id) unless Reward.find_by(name: Reward::REWARDS[:coffee], user_id: user.id, created_at: DateTime.current.all_month)&.present?
    end

    # 5% cash back reward
    if points >= 100 && user.products.this_year.count >= 10
      Reward.create(name: Reward::REWARDS[:cash_back], user_id: user.id) unless Reward.find_by(name: Reward::REWARDS[:cash_back], user_id: user.id, created_at: DateTime.current.all_month)&.present?
    end
    
    # movie reward
    if user.products.this_year.present?
      points = user.update_points(user.products&.this_year&.first&.created_at..user.products&.this_year&.first&.created_at+60.days)

      if points > 1000
        Reward.create(name: Reward::REWARDS[:movie], user_id: user.id) unless Reward.find_by(name: Reward::REWARDS[:movie], user_id: user.id, created_at: DateTime.current.all_month)&.present?
      end
    end

    # 4x Airport Lounge Access
    if (1000..4999).include?(points)
      Reward.create(name: Reward::REWARDS[:lounge], user_id: user.id) unless Reward.find_by(name: Reward::REWARDS[:lounge], user_id: user.id, created_at: DateTime.current.all_month)&.present?
    end
    
    # quarterly bonus
    unless Reward.find_by(name: Reward::REWARDS[:bounus], user_id: user.id, created_at: DateTime.current.all_quarter)&.present?
      quarterly_point = user.update_points(DateTime.current.all_quarter)

      if quarterly_point >= 2000        
        Reward.create(name: Reward::REWARDS[:bounus], user_id: user.id)
      end
    end
    

    return user.update(tier: User::TIER[:standard]) if points == 0 || user.tier.nil? || (0..999).include?(points)
    
    return user.update(tier: User::TIER[:gold]) if (1000..4999).include?(points)

    return user.update(tier: User::TIER[:platinum]) if points >= 5000

  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_user

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = @user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to user_url(@user), notice: "Product was successfully added." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to user_url(@user), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_user
      @user = User.find(params[:user_id])
    end
        
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :amount, :country, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: [@user, @product], class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h3><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h3>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.hidden_field :user_id, value: @user&.id %>
  
  <div class="my-2">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="my-2">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="my-2">
    <%= form.label :country %>
    <%= form.select(:country, Product::COUNTRY.invert.each {|key, value| [key, value]} ,{ }, class:"w-full py-2 rounded") %> 
  </div>

  <div class="inline">
    <%= form.submit class: "btn-primary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="inline-grid w-full grid-cols-3 p-2 bg-gray-100 rounded hover:bg-gray-200 my-0.5">
	<p class="w-full"> <%= product.name %> </p>

	<p class="w-full"> <%= product.amount %> </p>

	<p class="w-full"> <%= product.country.titleize %> </p>

</div>

app/views/products/edit.html.erb
<h3>Editing product</h3>
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h3>Products</h3>
    <%= link_to 'New product', new_user_product_path, class: "btn-primary" %>
  </div>

  <div id="products" class="min-w-full">
    <div class="grid grid-cols-3 p-1 bg-gray-200 mb-1">
      <strong> Name </strong>
      <strong> Amount </strong>
      <strong> Country </strong>
    </div>

      <%= render @products %>
  </div>
</div>

app/views/products/new.html.erb
<h3>New product</h3>
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="mx-auto">

  <div class="flex justify-between">
    <%= link_to '< Back', user_products_path, class:"btn-secondary" %>
    <%= link_to 'Edit this product', edit_user_product_path(@user, @product), class:"btn-secondary" %>
  </div>

  <%= render @product %>

</div>